config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'static_pages/home'

  devise_for :admins

  root 'static_pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  if Rails.env.production?
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable
  end

  has_many :posts, dependent: :destroy

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.order(created_at: :desc).limit(5)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_admin.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.order(created_at: :desc).limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
	  render_options = {
		  #do not allow any user-inputted HTML in the output.
		  filter_html: 			true,
		  #do not generate any <img> tags.
			#no_images: 				true,
			#do not generate any <a> tags.
			#no_links: 				true,
			#do not generate any <style> tags.
			#no_styles: 				true,
			#escape any HTML tags. This option has precedence over :no_styles, :no_links, :no_images and :filter_html which means that any existing tag will be escaped instead of being removed.
			#escape_html:  		true,
			#only generate links for protocols which are considered safe.
			#safe_links_only: 	true,
			#add HTML anchors to each header in the output HTML, to allow linking to each section.
			#with_toc_data: 		true,
			#insert HTML <br> tags inside on paragraphs where the origin Markdown document had newlines (by default, Markdown ignores these newlines).
			hard_wrap: 				true,
			#output XHTML-conformant tags. This option is always enabled in the Render::XHTML renderer.
			#xhtml: 						true,
			#add prettyprint classes to <code> tags for google-code-prettify.
			#prettify: 				true,
			#hash of extra attributes to add to links.
			link_attributes: { rel: 'nofollow' }
		}
	  renderer = HTML.new(render_options)

		extensions = {
			#do not parse emphasis inside of words. Strings such as foo_bar_baz will not generate <em> tags.
			no_intra_emphasis: 						true,
			#parse tables, PHP-Markdown style.
			tables: 												true,
			#parse fenced code blocks, PHP-Markdown style. Blocks delimited with 3 or more ~ or backticks will be considered as code, without the need to be indented. An optional language name may be added at the end of the opening fence for the code block.
			fenced_code_blocks: 						true,
			#parse links even when they are not enclosed in <> characters. Autolinks for the http, https and ftp protocols will be automatically detected. Email addresses and http links without protocol, but starting with www are also handled.
			autolink: 											true,
			#do not parse usual markdown code blocks. Markdown converts text with four spaces at the front of each line to code blocks. This options prevents it from doing so. Recommended to use with fenced_code_blocks: true.
			#disable_indented_code_blocks: 	true,
			#parse strikethrough, PHP-Markdown style. Two ~ characters mark the start of a strikethrough, e.g. this is ~~good~~ bad.
			#strikethrough: 									true,
			#HTML blocks do not require to be surrounded by an empty line as in the Markdown standard.
			lax_spacing: 										true,
			#A space is always required between the hash at the beginning of a header and its name, e.g. #this is my header would not be a valid header.
			#space_after_headers: 						true,
			#parse superscripts after the ^ character; contiguous superscripts are nested together, and complex values can be enclosed in parenthesis, e.g. this is the 2^(nd) time.
			#superscript: 										true,
			#parse underscored emphasis as underlines. This is _underlined_ but this is still *italic*.
			underline: 											true
			#parse highlights. This is ==highlighted==. It looks like this: <mark>highlighted</mark>
			#highlight: 											true,
			#parse quotes. This is a "quote". It looks like this: <q>quote</q>
			#quote: 													true,
			#parse footnotes, PHP-Markdown style. A footnote works very much like a reference-style link: it consists of a marker next to the text (e.g. This is a sentence.[^1]) and a footnote definition on its own line anywhere within the document (e.g. [^1]: This is a footnote.).
			#footnotes: 											true
		}
	  Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
	end

	class HTML < Redcarpet::Render::HTML
		include Rouge::Plugins::Redcarpet
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_about.html.erb
<h1>About</h1>
<%= image_tag "portrait.jpg" %>
<br><br>
<p>
  Welcome!  My name is Josh, I'm a programmer.  Sometimes I like to share things I find interesting or things I've learned.  This blog is implemented in Ruby on Rails and deployed to Heroku for hosting.  The source is available on Github.  Feel free to leave comments on the posts or start a discussion.
</p>
<a class="twitter-timeline" href="https://twitter.com/JoshuaGilless" data-widget-id="539626586694103040">Tweets by @JoshuaGilless</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Home", root_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider"></li>
      <li>
        <%= link_to 'https://github.com/jgilless' do %>
          <%= image_tag "GitHub-Mark-Light-32px.png", size: "16x16" %>
          @jgilless
        <% end %> 
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to 'https://twitter.com/joshuagilless' do %>
          <%= image_tag "Twitter_logo_white.png", size: "16x16" %>
          @JoshuaGilless
        <% end %> 
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to "Archive", posts_path %>
      </li>
    </ul>
    <!-- Left Nav Section -->
    <% if signed_in? %>
      <ul class="left">
        <li class="divider"></li>
        <li>
          <%= link_to('Logout', destroy_admin_session_path, method: :delete) %>
        </li>
        <li class="divider"></li>
      </ul>
    <% end  %>
  </section>
</nav>

app/views/layouts/_recent.html.erb
<h3>Recent Posts</h3>
<% @posts.each do |post| %>
  <%= link_to post.title, post %>
  <%= content_tag :div, class: "content" do %>
    <small><%= post.created_at.strftime("%b %d, %Y") %></small>
    <br>
    <br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Joshua Gilless" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="row">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'joshuagilless'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 3 %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 25 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="large-12 columns">
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="large-12 columns">
  <h1>All Posts</h1>

  <table>
    <thead>
      <tr>
        <th width="200">Title</th>
        <th width="500">Body</th>
        <th width="200">Last Updated</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, post %></td>
          <td><%= truncate(post.body, :length => 140) %></td>
          <td><%= post.updated_at.strftime("%Y-%m-%d at %H:%M") %></td>
          <td><%= link_to 'Show', post %></td>
          <% if signed_in? %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if signed_in? %>
    <%= link_to 'New Post', new_post_path %>
  <% end %>
<div>

app/views/posts/new.html.erb
<div class="large-12 columns">
  <h1>New post</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="large-9 columns">
  <p id="notice"><%= notice %></p>

  <h1>
    <%= @post.title %>
  </h1>

  <%= markdown @post.body %>

  <% if signed_in? %>
    <%= link_to 'Edit', edit_post_path(@post), class: "secondary button small" %> |
  <% end %>
  <%= link_to 'Back', root_path, class: "secondary button small" %>

  <%= render 'disqus' %>

</div>
<div class="large-3 columns right">
  <%= render 'layouts/about' %>
  <%= render 'layouts/recent' %>
</div>

app/views/static_pages/home.html.erb
<div class="large-8 columns">
  <h1>Posts</h1>
  <br>

  <dl class="accordion" data-accordion>
    <% @posts.each do |post| %>
      <dd class="accordion-navigation">
        <%= link_to post.title, "#panel#{post.id}" %>
        <%= content_tag :div, id: "panel#{post.id}", class: "content" do %>
          <%= post.description.to_s %>
          <br>
          <small><%= "Last updated on " + post.updated_at.strftime("%b %d, %Y") %></small>
          <br>
          <br>
          <%= link_to 'Read More', post, class: "secondary button tiny" %>
          <% if signed_in? %>
            <%= link_to 'Edit', edit_post_path(post), class: "secondary button tiny" %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "secondary button tiny" %>
          <% end %>
        <% end %>
      </dd>
    <% end %>
  </dl>

  <% if signed_in? %>
    <br>
    <br>
    <%= link_to 'New Post', new_post_path, class: "button small success" %>
  <% end %>
</div>
<div class="large-4 columns">
  <%= render 'layouts/about' %>
</div>